import numpy as np
from numba import jit

@jit(nopython=True)
def calculate_dth(pos,vel,teq):
    r=np.roll(pos,-1)-pos   #internode position vector
    dv=np.roll(vel,-1)-vel  #relative velocity between nodes
    mag=np.absolute(r)      #internode distance
    rh=r/mag                #internode unit vector
    th=np.angle(-rh/np.roll(rh,1))%(2*np.pi)    #angle between nodes
    dth=th-teq                                  #angle deviation between nodes
    return dth

@jit(nopython=True)
def calculate(pos,vel,teq): #calculate useful quantities
    ## update step
    r=np.roll(pos,-1)-pos   #internode position vector
    dv=np.roll(vel,-1)-vel  #relative velocity between nodes
    mag=np.absolute(r)      #internode distance
    rh=r/mag                #internode unit vector
    th=np.angle(-rh/np.roll(rh,1))%(2*np.pi)    #angle between nodes
    dth=th-teq                                  #angle deviation between nodes

    dthP=np.roll(dth,-1)                        
    dthM=np.roll(dth,1)

    o=1j*rh/mag                                 #unit normal vector
    oM=np.roll(o,1)                             #unit-1 normal vector
    oC=o+oM                                     

    velP=np.roll(vel,-1)
    velM=np.roll(vel,1)

    thdot=np.real(-oC*np.conj(vel)+o*np.conj(velP)+oM*np.conj(velM))
    thdotP=np.roll(thdot,-1)
    thdotM=np.roll(thdot,1)
    return r,dv,mag,rh,th,dth,dthP,dthM,thdot,thdotP,thdotM,o,oC,oM

@jit(nopython=True)
def edge_force(pos,vel,kr,gr,r,dv): #spring forces between nodes
    leq = 1
    fs = np.zeros_like(pos)             
    mag=np.abs(r)
    #boundary conditions
    mag[-1]=1                    
    dv[-1]=0.
    rh=r/mag
    SMag=kr*(mag-leq)   #hooke's law
    DMag=gr*np.real(dv*np.conj(rh)) #dissipation
    T=rh*(SMag+DMag)                
    fs = T-np.roll(T,1)
    return fs

@jit(nopython=True)
def passive_hinge_force(ke,disp,o,oC,oM,dth,dthM,dthP,thdot,thdotP,thdotM):
    # torsional springs 
    fE=ke*(dth*oC-dthP*o-dthM*oM) 
    # hinge dissipation 
    fD=disp*(thdot*oC-thdotP*o-thdotM*oM) 
    # boundary conditions
    fE[0] = ke*(-dthP[0]*o[0])
    fE[-1]= ke*(-dthM[-1]*oM[-1])
    fE[1] = ke*(dth[1]*oC[1]-dthP[1]*o[1])
    fE[-2]= ke*(dth[-2]*oC[-2]-dthM[-2]*oM[-2])
    fD[0] = disp*(-thdotP[0]*o[0])
    fD[-1]= disp*(-thdotM[-1]*oM[-1])
    fD[1] = disp*(thdot[1]*oC[1]-thdotP[1]*o[1])
    fD[-2]= disp*(thdot[-2]*oC[-2]-thdotM[-2]*oM[-2])
    return fE,fD


### agent's control policy
@jit(nopython=True)
def active_hinge_force_odd(ko,tau_max,dthP,dthM):
    # torque of each motor is tau = ka*(dthP - dthM)
    dth_tot = dthP-dthM
    # boundary conditions
    dth_tot[0]=0
    dth_tot[-1]=0
    # dth_tot[1]=dthP[1]
    # dth_tot[-2]=-dthM[-2]
    #saturating motors
    if ko!=0. and tau_max!=0.:
        th_cr = tau_max / ko
        dth_tot[dth_tot>np.abs(th_cr)] = np.abs(th_cr)
        dth_tot[dth_tot<-np.abs(th_cr)] = -np.abs(th_cr)
    tau = ko * dth_tot # N array with torques for each motor
    return tau


@jit(nopython=True)
def convert_torque_to_force(tau,o,oM):
    #convert active torques to forces
    fM = 1/2*tau *oM            #force on left neighbor due to torque generated by self
    fP = 1/2*tau *o             #force on right neighbor due to torque generated by self
    fself = -(fM+fP)            #action = reaction
    fM = np.roll(fM,-1)
    fP = np.roll(fP,1)
    fO = fself+fM+fP
    return fO

@jit(nopython=True)
def slide_force(vel,gam):#frictional force with the background (not super relevant)
    ff=np.zeros_like(vel)
    ff = -gam*vel
    return ff

@jit(nopython=True)     #gravitational force
def grav_force(pos,g):
    fg=g*np.ones_like(pos)
    return fg


@jit(nopython=True)
def wall_force(pos,vel,ks,gs,rad): #interaction force with landscape
    fw=np.zeros_like(pos)
    msk=np.imag(pos)<(rad)
    fw[msk]=-gs*vel[msk]-1j*ks*(np.imag(pos[msk])-rad)
    return fw

def get_initial(n_particles=13,amplitude=1e-2,y=2,seed=None):#initial conditions
    edge_len = 1
    assert amplitude < edge_len # if amp is greater than the edge length, 2 nodes can get too far
    if seed is not None:
        state = np.random.get_state()
        np.random.seed(seed)

    pos1 = np.full(n_particles, 1j * y,dtype=complex) # initialise height of all nodes at y
    pos1 += 1j * amplitude * (np.random.rand(n_particles)-0.5) # add noise in the vertical direction

    # initialise x values so that the edge length is constant
    for i in range(1, n_particles):
        z0 = pos1[i-1]
        z1 = pos1[i]
        dy = np.imag(z1) - np.imag(z0)
        dx = np.sqrt(edge_len - dy**2)
        pos1[i] += np.real(z0) + dx
    
    pos1 -= np.mean(np.real(pos1))

    vel1 = np.zeros_like(pos1)
    if seed is not None:
        # reset random state back to what it was
        np.random.set_state(state)
    return pos1, vel1

@jit(nopython=True)
def internode_angle(pos: np.ndarray) -> np.ndarray:
    dp = np.roll(pos,-1)-pos                                    #internode position vector
    dp_norm = dp/np.absolute(dp)                                #internode unit vector
    return np.angle(-dp_norm/np.roll(dp_norm,1))%(2*np.pi)      #angle between nodes

@jit(nopython=True)
def get_forces(action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant):
    r,dv,mag,rh,th,dth,dthP,dthM,thdot,thdotP,thdotM,o,oC,oM = calculate(pos,vel,teq=np.pi)
    fE,fD = passive_hinge_force(angle_stiffness,angle_damping,o,oC,oM,dth,dthM,dthP,thdot,thdotP,thdotM)    
    # tauO = active_hinge_force_odd(p['ko'],p['tau_max'],dthP,dthM)
    tauO = action
    
    fO = convert_torque_to_force(tauO,o,oM)
    fs=edge_force(pos,vel,edge_stiffness,edge_damping,r,dv)
    ff=slide_force(pos,background_friction)
    fw=wall_force(pos,vel,ground_stiffness,ground_damping,particle_radius)
    fg=grav_force(pos,gravity_constant)
    ftot=fE+fD+fO+fs+ff+fw+fg
    return ftot, thdot

@jit(nopython=True)
def velocity_verlet(steps, dt, particle_mass, action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant):
    for _ in range(steps):
        # Velocity Verlet integration
        f, _ = get_forces(action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant)
        vel = vel + f*0.5*dt/particle_mass
        pos = pos + vel*dt
        f, _ = get_forces(action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant)
        vel = vel + f*0.5*dt/particle_mass
    return pos, vel

@jit(nopython=True)
def velocity_verlet_with_thdot(steps, dt, particle_mass, action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant):
    for _ in range(steps):
        # Velocity Verlet integration
        f, _ = get_forces(action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant)
        vel = vel + f*0.5*dt/particle_mass
        pos = pos + vel*dt
        f, thdot = get_forces(action, pos, vel, angle_stiffness,angle_damping,edge_stiffness,edge_damping,background_friction,ground_stiffness,ground_damping,particle_radius,gravity_constant)
        vel = vel + f*0.5*dt/particle_mass
    return pos, vel, thdot

@jit(nopython=True)
def pos_angleeq_to_obs_dth3(pos, angle_eq):
    dth = internode_angle(pos) - angle_eq
    dth[0] = 0.
    dth[-1] = 0.
    dthP=np.roll(dth,-1)                        
    dthM=np.roll(dth,1)
    stacked = np.vstack((dthP, dth, dthM))
    stacked_inner = stacked.T[1:-1,:]
    obs_n = dict()
    for i in range(stacked_inner.shape[0]):
        obs_n[i] = stacked_inner[i]
    return obs_n

@jit(nopython=True)
def pos_angleeq_to_obs_dth_tot(pos, angle_eq):
    dth = internode_angle(pos) - angle_eq
    dth[0] = 0.
    dth[-1] = 0.
    dthP=np.roll(dth,-1)                        
    dthM=np.roll(dth,1)
    dth_tot = dthP-dthM
    stacked_inner = dth_tot[1:-1]
    obs_n = dict()
    for i in range(stacked_inner.shape[0]):
        obs_n[i] = stacked_inner[i]
    return obs_n

@jit(nopython=True)
def pos_angleeq_to_obs_small(pos, angle_eq):
    dth = internode_angle(pos) - angle_eq
    stacked_inner = np.array([[dth[1],dth[2]],[dth[2],dth[1]]])
    obs_n = dict()
    for i in range(stacked_inner.shape[0]):
        obs_n[i] = stacked_inner[i]
    return obs_n

@jit(nopython=True)
def pos_angleeq_to_obs_dth3_vel(pos, angle_eq, thdot):
    dth = internode_angle(pos) - angle_eq
    dth[0] = 0.
    dth[-1] = 0.
    dthP=np.roll(dth,-1)                        
    dthM=np.roll(dth,1)
    thdot[0] = 0.
    thdot[-1] = 0.
    thdotP=np.roll(thdot,-1)                        
    thdotM=np.roll(thdot,1)
    stacked = np.vstack((dthP, dth, dthM, thdotP, thdot, thdotM))
    stacked_inner = stacked.T[1:-1,:]
    obs_n = dict()
    for i in range(stacked_inner.shape[0]):
        obs_n[i] = stacked_inner[i]
    return obs_n

# class CrawlerEnv(ParallelEnv):
#     """
#     Simulates an Odd Crawler with variable nodes on a flat surface.

#     Observation space: the agent's control policy is implemented in active_hinge_force_odd,
#     which takes the following inputs:
#         - ko: parameter, odd elastic stiffness. scalar
#         - tau_max: parameter, maximum motor torque. scalar
#         - dthP: angle deviation between nodes rolled -1, (N,) array
#         - dthM: angle deviation between nodes rolled +1, (N,) array
#     ko and tau_max are parameters, so the only observations needed are
#     dthP and dthM. Both of these are computed from dth, the angle deviation between nodes. This
#     is an (N,) array

#     Action space: torque for each node, (N,) array
#     """
#     metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 100}

#     def __init__(
#             self, *,
#             render_mode=None,
#             render_fps=100,
#             n_particles=13,
#             physics_steps_per_timestep=10,
#             max_motor_torque = 9.0,
#             options = dict()
#             ):
#         self.window_size = 512  # The size of the PyGame window
#         self.metadata["render_fps"] = render_fps

#         self.agents = range(n_particles - 2)
#         self.render_mode = render_mode

#         self.n_particles = n_particles
#         self.particle_randomness = 0.1
#         self.particle_radius = 1/3.0
#         self.particle_mass = 0.2

#         self.dt = 3e-3 #integration time step
#         self.physics_steps_per_timestep = physics_steps_per_timestep # amount of integration timesteps per observation-action

#         self.max_motor_torque = max_motor_torque

#         self.gravity_constant = -1j*1
#         self.background_friction = 0.0

#         self.angle_eq = np.pi #equilibrium angles

#         self.angle_stiffness = 4.0
#         self.angle_damping = 0.42
#         self.ground_stiffness = 1e3
#         self.ground_damping = 5
#         self.edge_stiffness = 1e3
#         self.edge_damping = 5

#         self.reset(options=options)

#         self.observation_spaces = {agent: spaces.Box(
#             -np.pi, np.pi,
#             shape=(n_particles,),
#             dtype=np.float32
#         ) for agent in self.agents}
#         self.action_spaces = {agent: spaces.Box(
#             -self.max_motor_torque, self.max_motor_torque,
#             shape=(n_particles,),
#             dtype=np.float32
#         ) for agent in self.agents}

#         assert render_mode is None or render_mode in self.metadata["render_modes"]
#         self.render_mode = render_mode

#         """
#         If human-rendering is used, `self.window` will be a reference
#         to the window that we draw to. `self.clock` will be a clock that is used
#         to ensure that the environment is rendered at the correct framerate in
#         human-mode. They will remain `None` until human-mode is used for the
#         first time.
#         """
#         self.window = None
#         self.clock = None
    
#     def observation_space(self, agent):
#         return self.observation_spaces[agent]
    
#     def action_space(self, agent):
#         return self.action_spaces[agent]

#     def _get_obs(self):
#         return pos_angleeq_to_obs(self.pos, self.angle_eq)

#     def _get_info(self):
#         return dict()

#     def reset(self, seed=None, options: dict={}):
#         if options is None:
#             options = {}
#         # We need the following line to seed self.np_random
#         # super().reset(seed=seed)

#         self.pos, self.vel = get_initial(self.n_particles, amplitude=self.particle_randomness, seed=options.get("init_seed", None))
#         self.furthest_x = np.mean(np.real(self.pos))
#         self.camera_pos = np.mean(self.pos)
#         self.camera_vel = 0.0

#         observation = self._get_obs()
#         info = self._get_info()

#         if self.render_mode == "human":
#             self._render_frame()

#         return observation, info


#     def step(self, action):
#         self.pos, self.vel = velocity_verlet(self.physics_steps_per_timestep, self.dt, self.particle_mass, action, self.pos,  self.vel, self.angle_stiffness,self.angle_damping,self.edge_stiffness,self.edge_damping,self.background_friction,self.ground_stiffness,self.ground_damping,self.particle_radius,self.gravity_constant)
#         terminated = False

#         mean_x = np.mean(np.real(self.pos))
#         # if mean_x > self.furthest_x:
#         #     reward = mean_x - self.furthest_x
#         #     self.furthest_x = mean_x
#         # else:
#         #     reward = 0
#         reward = mean_x - self.furthest_x
#         self.furthest_x = mean_x


#         observation = self._get_obs()
#         info = self._get_info()

#         return observation, reward, terminated, False, info

#     def render(self, debug_renderer=None):
#         if self.render_mode == "human":
#             self._render_frame(debug_renderer=debug_renderer)
#         elif self.render_mode == "rgb_array":
#             return self._render_frame()

#     def _render_frame(self, debug_renderer=None):
#         if self.window is None and self.render_mode == "human":
#             pygame.init()
#             pygame.display.init()
#             self.window = pygame.display.set_mode((self.window_size, self.window_size))
#         if self.clock is None and self.render_mode == "human":
#             self.clock = pygame.time.Clock()

#         canvas = pygame.Surface((self.window_size, self.window_size))
#         canvas.fill((255, 255, 255))

#         node_pos = self.pos - self.camera_pos

#         scale = 20
#         offset = self.window_size/2 + 1j * self.window_size/2
#         node_pos = np.conjugate(node_pos * scale) + offset
#         origin_pos = np.conjugate(-self.camera_pos * scale) + offset

#         posx = np.real(node_pos)
#         posy = np.imag(node_pos)

#         # origin
#         pygame.draw.circle(canvas, (200, 200, 200), np.array([np.real(origin_pos), np.imag(origin_pos)]), 5)
#         font = pygame.font.Font(pygame.font.get_default_font(), 16)
#         text_surface = font.render('(0, 0)', True, (200, 200, 200))
#         canvas.blit(text_surface, dest=np.array([np.real(origin_pos), np.imag(origin_pos)])+4)

#         # grid lines
#         grid_line_spacing = 5
#         linex = np.fmod(np.real(origin_pos), grid_line_spacing * scale)
#         while linex < self.window_size:
#             pygame.draw.line(canvas, (200, 200, 200), np.array([linex, 0]), np.array([linex, self.window_size]), width=1)
#             linex += grid_line_spacing * scale
#         liney = np.fmod(np.imag(origin_pos), grid_line_spacing * scale)
#         while liney < self.window_size:
#             pygame.draw.line(canvas, (200, 200, 200), np.array([0, liney]), np.array([self.window_size, liney]), width=1)
#             liney += grid_line_spacing * scale

#         # ground
#         pygame.draw.line(canvas, 0, np.array([0, np.imag(origin_pos)]), np.array([self.window_size, np.imag(origin_pos)]), width=3)

#         # nodes
#         for i in np.arange(self.n_particles):
#             centre = np.array([posx[i], posy[i]])
#             pygame.draw.circle(canvas, (0, 0, 255), centre, self.particle_radius * scale)
        
#         # edges
#         c0 = np.array([posx[0], posy[0]])
#         for i in np.arange(1, self.n_particles):
#             c1 = np.array([posx[i], posy[i]])
#             pygame.draw.line(canvas, 0, c0, c1, width=3)
#             c0 = c1
        
#         # move camera
#         self.camera_pos += self.camera_vel
#         self.camera_vel *= 0.99
#         div = np.mean(self.pos) - self.camera_pos

#         dis_thresh = 1
#         if np.abs(div) > dis_thresh:
#             self.camera_vel += 0.0005 * div
#         elif np.abs(self.camera_vel) < 0.01:
#             self.camera_vel = 0
        
#         if debug_renderer is not None:
#             debug_renderer(canvas)

#         if self.render_mode == "human":
#             # The following line copies our drawings from `canvas` to the visible window
#             self.window.blit(canvas, canvas.get_rect())
#             pygame.event.pump()
#             pygame.display.update()

#             # We need to ensure that human-rendering occurs at the predefined framerate.
#             # The following line will automatically add a delay to
#             # keep the framerate stable.
#             self.clock.tick(self.metadata["render_fps"])
#         else:  # rgb_array
#             return np.transpose(
#                 np.array(pygame.surfarray.pixels3d(canvas)), axes=(1, 0, 2)
#             )

#     def close(self):
#         if self.window is not None:
#             pygame.display.quit()
#             pygame.quit()
